//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Id { get; set; }
        public Nullable<int> userId { get; set; }
        public string hoten { get; set; }
        public string sodt { get; set; }
        public string diachi { get; set; }
        public string congty { get; set; }
        public string quocgia { get; set; }
        public string tinhthanh { get; set; }
        public string quanhuyen { get; set; }
        public string phuongxa { get; set; }
        public string mazip { get; set; }
        public Nullable<int> diachimacdinh { get; set; }
        public string email { get; set; }
        public string note { get; set; }
    
        public virtual User User { get; set; }
    }
}
