//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OderItems = new HashSet<OderItem>();
        }
    
        public int id { get; set; }
        public string madh { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<decimal> tongdh { get; set; }
        public Nullable<System.DateTime> ngay_dathang { get; set; }
        public Nullable<int> phuongthucthanhtoan { get; set; }
        public Nullable<int> trangthaidonhang { get; set; }
        public string diachi { get; set; }
        public string hoten { get; set; }
        public string email { get; set; }
        public string sodt { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> trangthaivanchuyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OderItem> OderItems { get; set; }
        public virtual User User { get; set; }
    }
}
