//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductIntroduction
    {
        public int id { get; set; }
        public string giothieu { get; set; }
        public Nullable<int> id_description { get; set; }
    
        public virtual ProductDesc ProductDesc { get; set; }
    }
}
